### ISSUE TITLE
Sep ignores added code, not removed code

### ISSUE THREAD

**Issue by cflewis** [SoftwareIntrospectionLab/MininGit#11]
Check the logic of HunkBlame and Hunks to make sure the right hunks are being pulled out.

**Comment by linzhp** [comment]
Major data structure in FilePath needs to be changed for update_all to work. Currently FilePath only holds the file paths for one revision; new revision will override (except for files whose file_ids changes in new revisions) the old one. As a result, update_all only makes FilePath eventually holds the latest file paths.
HunkBlame will not work correctly unless this is fixed.

**Comment by cflewis** [comment]
Please open a new bug, this has nothing to do with this issue.

**Comment by cflewis** [comment]
Fixed in c5205a78713760508e95
