### ISSUE TITLE
MySQL Database .sql File Missing

### ISSUE THREAD

**Issue by firefly2442** [SoftwareIntrospectionLab/MininGit#128]
I can't seem to find the database design that sets up the MySQL database.  Is there an .sql file somewhere that I'm missing?  Thank you.

**Comment by cflewis** [comment]
No SQL file is needed, `Database.py` creates tables as required.

You do need to have a schema already set up in the MySQL database for cvsanaly to connect to. Look at the documentation for information about that.

**Comment by firefly2442** [comment]
Ahh, doh.  Sorry, thought I was missing something.  Seems to be working.  Cheers.
