### ISSUE TITLE
Git rename and copy detection flaky

### ISSUE THREAD

**Issue by apepper** [SoftwareIntrospectionLab/MininGit#132]
# The Issue

Git itself doesn't track renames or file copies. Even when using `git mv` it internally still added the content of that file to the new filename and removed the old file.

Having set that, it's possible to tell git to try to find copies or file moves. For this it uses heuristics, which hunks of which files are identical. If a file is moved without changed contend, git tells 'R100' (R for rename), which mean that the stated files have 100% content in common.

Since this is a heuristic this can go wrong. See the following example:

```
user@user:~/repos $ mkdir git_log_bug
user@user:~/repos $ cd git_log_bug
user@user:~/repos/git_log_bug $ git init
Initialized empty Git repository in /Users/user/repos/git_log_bug/.git/
user@user:~/repos/git_log_bug (master) $ echo "Hello World\nHello Universe" >> first_file.txt
user@user:~/repos/git_log_bug (master) $ echo "Hello World\nHello Universe" >> second_file.txt
user@user:~/repos/git_log_bug (master) $ git add first_file.txt second_file.txt
user@user:~/repos/git_log_bug (master) $ git commit -m "initial commit"
[master (root-commit) b996586] initial commit
 2 files changed, 2 insertions(+), 0 deletions(-)
 create mode 100644 first_file.txt
 create mode 100644 second_file.txt
user@user:~/repos/git_log_bug (master) $ git rm first_file.txt
rm 'first_file.txt'
user@user:~/repos/git_log_bug (master) $ echo "Hello some more" >> second_file.txt 
user@user:~/repos/git_log_bug (master) $ git mv second_file.txt renamed_second_file.txt
user@user:~/repos/git_log_bug (master) $ git add renamed_second_file.txt
user@user:~/repos/git_log_bug (master) $ git commit -m "second commit"
[master f11add4] second commit
 2 files changed, 1 insertions(+), 1 deletions(-)
 rename first_file.txt => renamed_second_file.txt (63%)
 delete mode 100644 second_file.txt
```

So far so good. Runing a `git log --name-status` without copy or rename detection yields the following (simplified):

```
user@user:~/repos/git_log_bug (master) $ git log --name-status
commit f11add4431f7cd8e93218ea2c222df1063dc8da1
Author: Alex <some.user@email.com>
Date:   Mon Sep 12 17:25:00 2011 +0200

    second commit

D       first_file.txt
A       renamed_second_file.txt
D       second_file.txt
```

Now with rename and copy detection it states this (simplified):

```
user@user:~/repos/git_log_bug (master) $ git log --name-status -C -M
commit f11add4431f7cd8e93218ea2c222df1063dc8da1
Author: Alex <some.user@email.com>
Date:   Mon Sep 12 17:25:00 2011 +0200

    second commit

R063    first_file.txt  renamed_second_file.txt
D       second_file.txt
user@user:~/repos/git_log_bug (master) $ git show -C -M f11add4431f7cd8e93218ea2c222df1063dc8da1
commit f11add4431f7cd8e93218ea2c222df1063dc8da1
Author: Alex <some.user@email.com>
Date:   Mon Sep 12 17:25:00 2011 +0200

    second commit

diff --git a/first_file.txt b/renamed_second_file.txt
similarity index 63%
rename from first_file.txt
rename to renamed_second_file.txt
index 7894def..194ec9c 100644
--- a/first_file.txt
+++ b/renamed_second_file.txt
@@ -1 +1,2 @@
 Hello World\nHello Universe
+Hello some more
diff --git a/second_file.txt b/second_file.txt
deleted file mode 100644
index 7894def..0000000
--- a/second_file.txt
+++ /dev/null
@@ -1 +0,0 @@
```

So all in all, it detects the wrong file renamed!

Now this could be ok, if it's consistend.
# The situation

**BUT** this is not consistend: `CVSAnalY` itself uses the flages `-M` and `-C` for rename and copy detection. The extension `CommitLOC` only uses `-M` (aka `--find-renames`, in my tests -C didn't made a difference) and Patches are also generated using `--find-renames` (`PatchLOC`, `Hunks` and indirectly `HunkBlame` uses those patches).
Since they don't always match this sometimes yield to `File id for some-renamed.file @  1234 not found`
# The solution?

One thing could be to enable copy detection on Patch creation to patch `CVSAnalY` and all the results of the patch creation. Whit this hunks of copied files essentially would be empty. But with this the file id should always be findable. @Lewisham and @linzhp: What do you think?

PS: this is related to https://github.com/SoftwareIntrospectionLab/repositoryhandler/

**Comment by linzhp** [comment]
I don't quite understand why "File id for some-renamed.file @ 1234 not found" could occur in this situation. Even though Git used the wrong file to rename, if CVSAnalY is able to identify that rename, it should still reuse some file_id for the renamed file instead of creating a new file_id. Then the renamed file is still able to track back without any error, though it might not be on the right path that human intended.

**Comment by apepper** [comment]
> I don't quite understand why "File id for some-renamed.file @ 1234 not found" could occur in this situation.

Maybe I haven't stated the problem correctly.

In Git: I observed a case, where two identical files (`a` and `b`) where present. In the next commit file `a` is deleted and file `b` renamed to `c` and some lines are changed.

In `CVSAnalY` core: Now `CVSAnalY` with `git log -M -C` reads, that `a` is deleted and `b` renamed and modified to `c` and stores those information with the commit id 1234.

In `Patches`: This uses `git show -M` and in that diff file, git identifies `b` as the deleted file and a rename from `a` to `c`! PatchParser parses that file, but can not find the file id for `b` at that commit, because `CVSAnalY` core only stored the "new" name for that file: `c`. With this Patches now reports "File id for b @ 1234 not found".

**Comment by linzhp** [comment]
Yes, but if a and b were identical, it doesn't matter which is renamed to c, and which is deleted, right? As long as Patches finds that c is renamed from some file, though it identifies a instead of b, it is fine; it will search for the file_id of a instead of b in the commits 1234. And since it already knows that b is deleted, why it is still searching for file_id of b @ 1234?

It looks like this is an issue not quite related to file rename, but related to the processing of deleted files.

**Comment by apepper** [comment]
@linzhp: You are right, that the wrongly detected rename is not causing problems, but the "wrongly" deleted file `b`. This is still an issue anyhow, since deleted files are showing up in the git patch with all lines of that file removed (e.g. if `b` had 5 lines, the delete-patch would show up 5 deleted lines). Because of this, no delete-patch is stored since `Patches` can't find a `file_id`.

**Comment by linzhp** [comment]
Deleted files are shown in Git patch like this:

a/path/to/a/deleted/file
b/dev/null

Normally, PatchParser use the second file path as file name. However, when the second path is /dev/null, it uses the first path. Now the problem is, the first path doesn't exist if it is deleted in that revision. We need to add some logic to treat delete action differently.

**Comment by apepper** [comment]
If path/to/a/deleted/file is deleted in revision x, there is a entry in the action table with commit x, this file and the type 'D'. Als this get's stored to the patch table.

It get's complicated, if action table thinks, that path/to/a/deleted/file is renamed to some other file (with a new name) but patches thinks, that path/to/a/deleted/file is deleted (which is the case if renamed and copy detection of git mix those up).

For better debugging:
`CVSAnalY` core uses `git log --topo-order --pretty=fuller --parents --name-status -M -C --cc --decorate=full`. The flag `-M` and `-C` are the importend one. `man git-log` clames, that file-renames are also shown, when using the flag `-C`. So the flag `-M` should be obsolete here.
`Patches` uses `git show --find-renames --pretty=format`, where `--find-renames` is a aliase for `-M`.

What would happen, if we drop the `-M` from git log and instead of using `--find-renames` for git show, using `-C`? `PatchParser` whould neede to be adjusted to understand the following:

```
diff --git a/original_file.txt b/copied_file.txt
similarity index 100%
copy from original_file.txt
copy to copied_file.txt
```

Also hunks and hunksblame somehow should deal with copies. Currently copies are not detected with Patches, Hunks and HunkBlames, so changes that where made prior to the file copy can not be traced by HunkBlames. In general I think it's worth the effort to come up with a "copy detection" for Patches/Hunks/HunkBlames. @Lewisham and @linzhp: what do you think?

**Comment by apepper** [comment]
Patches now parses file copies. Adjusted `CommitsLOC` to verify the results. In my tests MalformedHunkHeader and File id for … not found droped by 4 to 5 items and the mismatches between PatchLOC and CommitsLOC dropped by 4.
