### ISSUE TITLE
update_all doesn't work in FilePath

### ISSUE THREAD

**Issue by linzhp** [SoftwareIntrospectionLab/MininGit#14]
Major data structure in FilePath needs to be changed for update_all to work. Currently FilePath only holds the file paths for one revision; new revision will override (except for files whose file_ids changes in new revisions) the old one. As a result, update_all only makes FilePath eventually holds the latest file paths.
HunkBlame will not work correctly unless this is fixed.
I have two solutions in mind:
1. Change the major data structure in FilePath to store what currently in self.**dict**['adj'] for each revision.
2. Remove update_all, cache FilePath or some part of it for some revision whenever needed.

**Comment by cflewis** [comment]
Yes, I was thinking of something like option 2.

If you called update_for_revision() inside get_path() each time, that would keep the code together where it makes sense. This would mean the adjacency matrix was always correct for each commit.

You don't need to worry about caching for now... it's going to be a little slow, but we're just working towards getting something that works, so a bit slow on the CPU is OK. 

If you really wanted to cache it, I guess you would make a dictionary indexed by the commit ID, with each adjacency matrix in there. But don't worry about that for now ;)

**Comment by cflewis** [comment]
Closed in 5a3a0edf6fc108d10235
