### ISSUE TITLE
Feature Request: List Available Extensions

### ISSUE THREAD

**Issue by carlsonp** [SoftwareIntrospectionLab/MininGit#150]
I'm not sure if there is documentation surrounding them but it sounds like the extensions are plugins for the base software?  It would be great if there was a way to list the extensions that are available when running the program.  Or, perhaps just add all the ones that can be run somewhere in --help.

**Comment by linzhp** [comment]
The available extensions can be found is ls command under "extensions" directory

**Comment by carlsonp** [comment]
Ahh ok thanks!  I would still suggest adding this to the Readme somewhere because I was a little confused by this.  Cheers.

**Comment by linzhp** [comment]
Thanks for the suggestion. I've just added that to --help

**Comment by philip-iii** [comment]
Unknowingly I implemented listing of the available extensions yesterday as I was also a bit dissatisfied with the discoverability of extensions. In fact I just put up a pull request regarding this (before I discovered this issue). See https://github.com/SoftwareIntrospectionLab/MininGit/pull/157

**Comment by linzhp** [comment]
Thanks!
