### ISSUE TITLE
Rename cvsanaly to MininGit in the README and the executable

### ISSUE THREAD

**Issue by cflewis** [SoftwareIntrospectionLab/MininGit#151]
The README/docs/executable still refers to `cvsanaly`, and they should say `miningit` instead.

**Comment by apepper** [comment]
Well, _everything_ still references `cvsanaly`.

E.g.:
- file and folder names
- Readme

**Comment by cflewis** [comment]
Well, yes, that list was just a start :)

## 

Chris Lewis

On Wed, Feb 29, 2012 at 12:53 AM, Alexander Pepper
reply@reply.github.com
wrote:
