### ISSUE TITLE
Multiple commits being flattened to the same date.

### ISSUE THREAD

**Issue by supertri** [SoftwareIntrospectionLab/MininGit#17]
If you run the following commands on the db:
select author_id from scmlog where date='2010-10-04 11:56:50';
select id from scmlog where date='2010-10-04 11:56:50';

You will find that there are 13 different commit ids associated with this date, by two different authors.

The date does not match what is in the database, because cvsanaly flattened them to have the same time, for reasons unknown. They are multiple different commits.

**Comment by cflewis** [comment]
Closing for now per discussion on email list. No obvious course of resolution.
