### ISSUE TITLE
content_loc off by 1

### ISSUE THREAD

**Issue by xyzhu** [SoftwareIntrospectionLab/MininGit#21]
the loc in content_loc is 1 less than it should be.

**Comment by cflewis** [comment]
I need a better bug report than this. Show me an example. Does it happen to all records?

Remember that most files end with a newline. These are filtered by the SQL query. I could add an extra +1 line, but then if there is a file that doesn't end with a newline, it will be off by one.

**Comment by supertri** [comment]
For an example:

fixcache.xml generates a contents table directly, without the creation of explicit files (This is also a pretty human-readable file). However, I believe the LOC for these explicitly written contents entries are off by one. 

For example the LOC for this contents entry:
  <content id="1" commit_id="1" file_id="1" content="a;&#xA;b;"/>
are reported as 1, not 2.

**Comment by cflewis** [comment]
Added one to LOC, closed by 86d75641994e8ceb4cb17c65d545cb8e2a48f5ee
