### ISSUE TITLE
Missing info from README

### ISSUE THREAD

**Issue by supertri** [SoftwareIntrospectionLab/MininGit#23]
It looks like Python MySQLDB is not optional if you are you using a mysql db. 

Also, the directory where repository handler lives needs to be in PYTHONPATH.

**Comment by supertri** [comment]
Plus, instructions for setting up a config file would be handy in the readme; if you do not specify a password in the config file it seems the error message reads that the username is unspecified.

Also, after updating cvsanaly from version control I am assuming we just need to run python setup.py install again to build from the command line.

**Comment by supertri** [comment]
Actually, a separate README file for installing and running the new code would be very helpful. The current README file is even slightly inconsistent with the actual requirements.

**Comment by cflewis** [comment]
Edited requirements and README to point to SoftwareIntrospectionLab on
GitHub. Couple of lagnauge changes in README.

Closed by 2102afb09714103b93b6a917fa9ccc83e1930867.
