### ISSUE TITLE
HunkBlame: no previous commit found

### ISSUE THREAD

**Issue by cflewis** [SoftwareIntrospectionLab/MininGit#28]
"No previous commit found" comes up a lot (hundreds or thousands) when running HunkBlame on Voldemort. Is this something we should be worried about?

**Comment by linzhp** [comment]
I traced down the hunks where "no previous commit found" exception is thrown, and found that it was a bug in cvsanly. For those hunks, there is truly "no previous commit" if we look at action_files table. Some of such hunks (in soe ejw_xzhu1 db) are: 4779, 4781, 4793, 4797). However, they have previous commits in git. Which means cvsanaly is wrong.

**Comment by cflewis** [comment]
OK, this one is going to have to drop down the priority list. Fixing that bug is going to require some hard work that we certainly don't have time for by MSR, and I don't have to for it before February 10th or so due to the number of papers I have to do.

**Comment by cflewis** [comment]
Currently hoping this is a symptom of GH-35.

**Comment by linzhp** [comment]
I checked several such hunks, the associated files all have many copies. It is very likely to be a symptom of GH-35

**Comment by cflewis** [comment]
Alright, if it's a symptom of GH-35 I'm going to close with Won't Fix, as its working as intended (just not as expected :) )
