### ISSUE TITLE
Is the Git parser missing add events?

### ISSUE THREAD

**Issue by cflewis** [SoftwareIntrospectionLab/MininGit#35]
See Apache repo for example. It could either be missing the add events, or the add events aren't in there. If they're not in there, not a lot we can do.

```
select distinct(actions.file_id) from actions, scmlog, file_types
where actions.file_id=file_types.file_id and file_types.type='code'
and actions.commit_id=scmlog.id and scmlog.repository_id=1 and
actions.file_id not in (select file_id from actions where type='A');
```

**Comment by supertri** [comment]
The missing add events may be a result of the many file ids associated with a particular file.

select f.file_name, count(f.file_name) as number from files f, file_types ft
where ft.file_id = f.id
and f.repository_id = 1
and ft.type = 'code'
group by f.file_name
order by number desc
limit 0,10

**Comment by cflewis** [comment]
Update: I've stepped through the Git parser itself on toy examples. There's no reason to believe that the parser itself is bad, it appears to be doing everything correctly. There must be something wrong with the interface between it and the database.

**Comment by cflewis** [comment]
I'm getting closer. Appears that sometimes the parser doesn't send the writer stuff to the temp log. With the temp log empty, no processing takes place.

Problem in the way DBTempLog is fed information, I think.

**Comment by cflewis** [comment]
Looks like the comment from Supertri is correct.

Testing on Voldemort, a file comes up, called build-readonly-store.sh. This doesn't have an add event for a good reason: it was created by a copy.

```
commit 8219a4aed922b0819281cc62e504e4706232c808 0bacb95dd6a2283b60ea1c418089920a0d73e79e
Author:     Jay Kreps <jay.kreps@gmail.com>
AuthorDate: Mon Jan 19 04:56:49 2009 +0000
Commit:     Jay Kreps <jay.kreps@gmail.com>
CommitDate: Mon Jan 19 04:56:49 2009 +0000

    Cleanup. Add support for removing versioning from voldemort config. Misc. improvements for read-only store. Make external sort multithreaded in the sort phase.

M   .classpath
M   TODO
C074    bin/sort.sh bin/build-readonly-store.sh
```

C074 is the copy command. I don't know enough about Git's logs yet to understand what the number means. The parser just matches on `^([RC])[0-9]+[ \t]+`.

This is correctly recorded in the file_copies table, but there will be no add event stored. The event stored is 'C'.

We will need to begin discussing how to move ahead in terms of file paths and file resolution.

**Comment by supertri** [comment]
Is every new file id for the same file prefaced by a C event under the old id? I believe there are also many file ids that only exist for one M event.

**Comment by cflewis** [comment]
Please rephrase your question, I don't know what you mean.

**Comment by supertri** [comment]
Sorry. It looks like there are some file_ids with no A event and also no matching C event:

In Apache httpd:

select \* from actions where actions.file_id in (select files.id from files where files.file_name='mod_cache.h')

**Comment by cflewis** [comment]
This looks like there is something wrong with file name resolution: file IDs 8423 and 13207 should have the same path, unless they are in different branches. 8423 is the addition of the file, 13207 is when it appears as modified (but not created).

Gut feeling: the files are in different branches. A quick print statement should verify this.

**Comment by cflewis** [comment]
Yeah, as suspected:

```
DBG: DBContentHandler: Looking for path 9://modules/experimental/mod_cache.h in cache
DBG: DBContentHandler: Looking for path 9://modules/experimental/mod_cache.h in cache
DBG: DBContentHandler: Looking for path 9://modules/experimental/mod_cache.h in cache
DBG: DBContentHandler: Looking for path 9://modules/experimental/mod_cache.h in cache
DBG: DBContentHandler: Looking for path 1://modules/experimental/mod_cache.h in cache
DBG: DBContentHandler: Looking for path 10://modules/experimental/mod_cache.h in cache
```

The numbers in front of the URIs indicate the branch ID. A file can exist in many branches, and cvsanaly tracks them individually. However, I'm stumped as to whether these files can be tracked back to the original locations. The `file_links` table seems to be where file paths are built, but not how files are related to each other. The `file_copies` table certainly does not hold information about files being duplicated to branches.

I don't think this is a bug. I think this is cvsanaly working as intended. The question is whether this intention matches our intuition about how it _should_ work, to which I believe the answer is no.

However, as we've discussed privately, there's no obvious plan of action to modify this behavior that is conclusively "better".

**Comment by cflewis** [comment]
Closing for now, discussions have indicated that this is probably working as intended, no change to cvsanaly is necessary. The `--branch` argument is a workaround for us, as we can just track `master`.
