### ISSUE TITLE
Extra delete events 

### ISSUE THREAD

**Issue by supertri** [SoftwareIntrospectionLab/MininGit#51]
Some file_ids (e.g. file 10066) that are deleted multiple times: e.g. participate in multiple delete
actions.

select \* from actions a, scmlog s where a.file_id = 10066 and a.type='D'
and a.commit_id = s.id;

The commit messages indicate a tool called cvs2svn did it in order to create svn tags when Apache upgraded from cvs to svn. We need to understand why cvs2svn would do this, and how to fix it. 

Right now, it is very difficult to tell which files actually exist in the repository at a particular point in time, or what a file_id is referencing.

**Comment by cflewis** [comment]
This is making me think that FixCache should just ignore anything before the svn migration. I think this is just cvs2svn doing stuff that is deliberately screwing around with the commit history in a way that's going to make things look unreliable.

I don't think this is cvsanaly doing anything wrong, so unless there's a compelling reason to believe cvsanaly is doing something wrong, I'm going to wishlist this.

Re: number of files in repository; there is already an issue at GH-47 about this.

**Comment by cflewis** [comment]
There is one file that does this with Voldemort. File ID 232355 appears deleted twice: once when it was deleted in a feature branch, then it appears to do so again when the commit is applied to master.

This underlines the complexity of the branching problem that we have. Only one real delete takes place; it is just applied to two sets of source that we are tracking. With no reliable means of resolving identical commits (they are hashed differently), I don't see how this will be easily resolved.

**Comment by cflewis** [comment]
GH-35 symptom, closing with Won't Fix.
