### ISSUE TITLE
Merge commits are being counted in Git

### ISSUE THREAD

**Issue by cflewis** [SoftwareIntrospectionLab/MininGit#71]
Merge commits are being counted in Git, but should be ignored. However, the Git parser changes I tried didn't work if a merge commit was at the head, which seemed to prevent it pulling a branch name down. I need to look at this more closely.

**Comment by cflewis** [comment]
The commit where I did this was https://github.com/SoftwareIntrospectionLab/repositoryhandler/commit/01448d18ae68366a8b34c885dbde7fb72d99e20a

This was breaking the Git parser. It needs a bit of thought as to what is going on. It'll need to look at what the Git log is outputting, how the parser is going through it, and then working out whether the parser needs changing (either by adding to the regex, feeding some default information to it, changing some logic etc etc) or whether there is another flag to pass on the command-line that will fix it.

Always choose sending a flag where possible. This makes life a lot easier.

**Comment by cflewis** [comment]
I do have on my laptop a version of Voldemort that is good for testing where a merge is at the head, and I'll zip that up and upload it somewhere when I can*
- You'll probably have to remind me to do this :)

**Comment by apepper** [comment]
Hi Chris.
Why is there a need to ignore merge commits? What are the reasons?

Merge commits are also importent. Sometimes (especially with bigger merges) alot of code is touched during a merge so why not store it to `scmlog`?

Greetings from Berlin

**Comment by cflewis** [comment]
We decided to ignore merge commits in Git because Git will put all the data of a merge in that commit, as well as interleaving the commit data into the history. This means you see the same actions twice. We're not missing data, unless the repo owners do something like rebasing everything to squash into single commits (and if they do that, I don't know if we're going to ignore it or not).

I'm happy to accept a pull request with an option to enable or disable this (default to ignoring merges), as I can see the value of wanting to know how many merges a repo has. However, the schema doesn't have a flag for "is_merge" or something like that, so you'd have to go by the commit message alone.

I'm fairly sure @linzhp closed this one, but will leave to him to close.

**Comment by linzhp** [comment]
Fixed in fb6f8ad6e43ccc3e8fa4bfcc5e1c2a89959b5793

**Comment by apepper** [comment]
See pullrequest #95.

Now it's possible to configure if merge commits are wanted.

@Lewisham I found that the log of a merge commit DOESN'T contain all the changes of the merged trees. So this DOESN'T count the changes twice. So it should be save to use this information without duplicates.
