### ISSUE TITLE
Multiple repo import

### ISSUE THREAD

**Issue by cflewis** [SoftwareIntrospectionLab/MininGit#72]
cvsanaly should be able to take a list of repos and process them one-by-one, so large scale imports don't involve multiple chained together commands.

**Comment by philip-iii** [comment]
As far as I remember, one of the LibreSoft tools was serving this very purpose (Blackbird https://projects.libresoft.es/wiki/blackbird). I am not sure what state it's in at the moment, but perhaps it (or parts of it) could be reused for the purpose...

**Comment by cflewis** [comment]
This is a good idea, but my intentions were much more humble :) I just
wanted a text file which can be fed in with multiple repo locations
and then run through them one by one. We use
[Jenkins](http://www.jenkins-ci.org) internally for these sort of
automation tasks.

## 

Chris Lewis

On Mon, Apr 11, 2011 at 5:40 AM, philip-iii
reply@reply.github.com
wrote:

**Comment by cflewis** [comment]
Closing to clean up my dash.
