### ISSUE TITLE
Hunk file ID resolution is branch-inspecific

### ISSUE THREAD

**Issue by cflewis** [SoftwareIntrospectionLab/MininGit#79]
A possible reason for why the file ID lookup in Hunks gets multiple results is because it doesn't take into account what branch we're on. The SQL should be modified to try and find out the branch, maybe from the patch parser/getter.

**Comment by linzhp** [comment]
@Lewisham, could you show how to reproduce this issue? I am trying to understand #96.

**Comment by cflewis** [comment]
Hmm, I'm not sure how this one now works with the new file_path lookup in place.

Look at the code as it used to be: https://github.com/SoftwareIntrospectionLab/cvsanaly/blob/ea1ff8ee748523e11247a5c24ec16ca7c2f6ac62/pycvsanaly2/extensions/Hunks.py#L305

The code was a very poor attempt at trying to resolve file IDs, when often there were multiple matches, and it didn't look at branches at all.

File paths doesn't check either: https://github.com/SoftwareIntrospectionLab/cvsanaly/blob/develop/pycvsanaly2/extensions/FilePaths.py#L153

I don't think this is related to #96 apart from that #96 is related to a feature that was supposed to workaround this issue. The branching logic in cvsanaly is difficult, and, for what we were doing, it was better to ignore it. By ignoring branches, you don't get this issue.

**Comment by apepper** [comment]
With #129 this should not be an issue anymore. @linzhp and @Lewisham: Please close.
