### ISSUE TITLE
Share file path

### ISSUE THREAD

**Issue by linzhp** [SoftwareIntrospectionLab/MininGit#81]
It would be more efficient to share adjacency matrices of file paths across extensions in the same run. Currently, each extension builds file paths on its own.

**Comment by cflewis** [comment]
Hmmm, I quite like that Extensions are essentially atomic.

Let me know how you plan to solve this one before you start work on it.

**Comment by linzhp** [comment]
Actually, it turned out to be a pretty quick fix, though I haven't tested it yet. See
https://github.com/linzhp/cvsanaly/commit/2606d4f918e1a617e76cfdf196fb23a49747094d
Note that most changes in that commit are for PEP-8 cleanup, only those in FilePath are the fix.

**Comment by cflewis** [comment]
OK, looks good to me. Test it then push it.

## 

Chris Lewis

On Sat, Apr 23, 2011 at 1:44 PM, linzhp
reply@reply.github.com
wrote:

**Comment by cflewis** [comment]
Are you still planning to push this, or did you find something wrong with it? 

I want to get a stable release to master next week.

**Comment by linzhp** [comment]
pushed, sorry for the lateness.
