### ISSUE TITLE
[Bug] Agressive patch-trimming causes hunk-extraction failures

### ISSUE THREAD

**Issue by philip-iii** [SoftwareIntrospectionLab/MininGit#92]
Foreword: This has been an issue that has been nagging for quite a while, but so far I haven't had the time to look into it. Now with a fix suggestion.

It seems that when patches are being processed some newlines which are part of the context get trimmed as well. This in turn results in PatchParser failing in iter_hunks (lines 280-286):

```
    while orig_size < hunk.orig_range or mod_size < hunk.mod_range:
        hunk_line = parse_line(iter_lines.next())
        hunk.lines.append(hunk_line)
        if isinstance(hunk_line, (RemoveLine, ContextLine)):
            orig_size += 1
        if isinstance(hunk_line, (InsertLine, ContextLine)):
            mod_size += 1
```

iter_lines.next() tries to access an invalid index while mod_size and orig_size are still less than the orig)range and mod_range of the hunk (which has asymmetric context) and subsequently jumps out of the loop and out of the method. Take for example this patch from LibreSoft's CVSAnalY:

```
diff --git a/pycvsanaly2/extensions/FilePaths.py b/pycvsanaly2/extensions/FilePaths.py
index 5b76ec2..3c40cbf 100644
--- a/pycvsanaly2/extensions/FilePaths.py
+++ b/pycvsanaly2/extensions/FilePaths.py
@@ -153,6 +153,14 @@ class FilePaths:

         return path

+    def get_filename (self, file_id):
+        adj = self.__dict__['adj']
+        assert adj is not None, "Matrix no updated"
+        try:
+            return adj.files[file_id]
+        except KeyError:
+            return None
+
     def get_commit_id (self):
         return self.__dict__['rev']
```

This is the data stored in the patches table, whereas the original patch has another empty line at the end of the context. There are a few ways to address this:
- make the while loop more robust (local, quick, not fixing the real upstream issue however may cause further trouble down the road), e.g. 
  
     while orig_size < hunk.orig_range or mod_size < hunk.mod_range:
          try:
              l = iter_lines.next()
          except StopIteration:
              #Do something about it?
              print l
          hunk_line = parse_line(l)
          hunk.lines.append(hunk_line)
          if isinstance(hunk_line, (RemoveLine, ContextLine)):
              orig_size += 1
          if isinstance(hunk_line, (InsertLine, ContextLine)):
              mod_size += 1
  
  (or add new lines at the end of patches compulsively)
- fix the issue with the patches processing early on (better long term, possibly further implications?), e.g. Patches.py, lines 50-53:
  
  ```
      try:
          self.repo.show(self.repo_uri, self.rev)
          self.data = to_utf8(io.getvalue().strip()).decode("utf-8")
          done = True
  ```

The strip() call needs to be removed from io.getvalue().
- fix both (unchecked iterators although potentially faster pose risks for potential quiet failures like the one described in this issue; if there is no specific reason for trimming the patches explicitly, then they should be left as they are I guess)

In the cvsanaly dataset (LibreSoft repo, snapshot Nov-2010) I got about 150 new hunks (3645 vs 3494 before). I still have to investigate whether there are other omitted hunks (but that would be due to other issues) or how it stacks up on larger repos (will take some time)

Opinions?

Cheers,

Philip

P.S. Sorry for the crude presentation, I need to finally figure out how to reference code from the source tree directly, but ultimately I need to set up a fork so I can potentially submit pull-requests directly.

**Comment by philip-iii** [comment]
I've just realized that with the current version there are apparently many other hunks missing. The base line I used for comparison is a bit dated (about a month perhaps?). The baseline with the current version is not far off (3491) however, there are apparently other hunks missing for whatever reason (which would mean that there are others present that were not there in the older baseline). 

So while the suggestions above do fix some issues, there seem to be some others that need further investigation.

**Comment by cflewis** [comment]
Yes, we're currently working on hunk resolution due to changes with file paths.

It looks like you have investigated this issue throughly (or at least, more than I have time for). I am happy to accept a pull request which removes the .strip() from Patches.py. Run a test or two to see if things match your expectations, do a pull request and I or @linzhp can merge in.

**Comment by philip-iii** [comment]
I think you have fixed this in https://github.com/SoftwareIntrospectionLab/cvsanaly/commit/7befbce96f553ecf258ecee711a9db4bb4b9a05a It is a variation of the first proposed solution and seems to produce the same results as both proposed solutions. I didn't get around to setting up github sooner, but your solution seems more appropriate anyway! Cheers!

**Comment by cflewis** [comment]
Cool! That patch should have been in there a long time ago. I submitted it as a patch upstream where I got it from, and I guess I decided I was going to wait for upstream to be fixed, but it never was, then I forgot :)

I'll close this one as "fixed by happy accident."
